### PR TITLE
use transform-react-inline-elements babel plugin for faster stateless…

### PR DESCRIPTION
**Pull request by n0izn0iz**
… react components

see https://www.bram.us/2017/05/08/45-faster-react-stateless-functional-components/
Probably not a 45% improvement tho

### CODE REVIEW

**Comment by vincentfretin** [comment]
You enabled it for development only. It's not recommended to enable it on development because you can have hard to debug issues. If you want to enable it for prod, you need to add it to webpack.config.js.

**Comment by vincentfretin** [comment]
Please commit yarn.lock as well. If nobody object, go for merge.

**Comment by vincentfretin** [comment]
My remark for hard to debug in develop applies for transform-react-constant-elements actually, not transform-react-inline-elements.
So I guess it's ok if you put transform-react-inline-elements in webpack.dev.config.js too.

**Comment by n0izn0iz** [comment]
Don't merge, I'll reduce the PR to one commit

**Comment by vincentfretin** [comment]
LGTM, please merge.

**Pull request merged**
