### PR TITLE
Fix notification mails links when debate is using v2

### PR DESCRIPTION
**Pull request by n0izn0iz**
https://bluenove.atlassian.net/browse/DEVAS-1040

I'm not sure this will fix it

### CODE REVIEW

**Comment by vincentfretin** [comment]
This should fix it indeed.

**Comment by n0izn0iz** [comment]
I can't find a way to check the content of outbound emails locally :(

**Comment by ayyazdaniaryan** [comment]
@n0izn0iz Here's how you can do it:
- You'll have to do a bit of database inspection to find the Notification ID object associated with a post created, then use the `/data/Notification/<id>/mail_html_preview` to view the notification message.

**Comment by n0izn0iz** [comment]
nofix

**Comment by n0izn0iz** [comment]
Actually, request is not None when mails are rendered in the browser views but it's None in other cases so we need both

**Pull request merged**
