### PR TITLE
Fix num posts

### PR DESCRIPTION
**Pull request by ayyazdaniaryan**
The header statistics should now show the count of ALL posts that are done on the root idea.

These include:

- proposal posts (phase1)
- assembl posts (phase N)
- assembl posts on n columns

### CODE REVIEW

**Comment by vincentfretin** [comment]
As far I understand, we now want to count posts from all phases?
Previously we didn't want to count phase1 posts when we were in phase2.
I think you can revert all what you did, and just remove those lines https://github.com/assembl/assembl/blob/cdc3c87dad9cb669ab9c89a637a0b07ae9676da6/assembl/graphql/schema.py#L588-L592 and fix the failing test.

**Comment by ayyazdaniaryan** [comment]
Changes made.

**Comment by vincentfretin** [comment]
LGTM

**Comment by vincentfretin** [comment]
please wait for travis to finish

**Pull request merged**
